Refactor Docker setup and scripts; consolidate build commands, add ASGI support, update documentation, remove Django image

diff --git a/docker/tna-python-dev/bin/tna-wsgi b/docker/tna-python-dev/bin/tna-wsgi
--- a/docker/tna-python-dev/bin/tna-wsgi
+++ b/docker/tna-python-dev/bin/tna-wsgi
@@ -2,7 +2,8 @@
 
 set -e
 
-echo "Running tna-run for Python dev...";
+echo "Running development server..."
+echo
 
 # Get the application
 APPLICATION=$1
@@ -10,10 +11,10 @@ APPLICATION=$1
 # Error if no application is passed
 if [ -z "$APPLICATION" ]
 then
-  echo -e "Error: application not specified in tna-run\n";
+  echo -e "Error: application not specified in tna-wsgi\n";
   echo "PARAMETERS"
   echo "  application          the Python package you want to run"
-  echo "                       Example: tna-run my_app:app";
+  echo "                       Example: tna-wsgi my_app:app";
   exit 1
 fi
 
@@ -29,18 +30,17 @@ then
   tna-node "$NPM_DEVELOP_COMMAND"
 fi
 
-# Set defaults for environment variables if they are not set
-[[ -z $LOG_LEVEL ]] && LOG_LEVEL=debug
-[[ -z $WORKERS ]] && WORKERS=3
-[[ -z $THREADS ]] && THREADS=1
-[[ -z $TIMEOUT ]] && TIMEOUT=600
-[[ -z $KEEP_ALIVE ]] && KEEP_ALIVE=5
-
 # Try using the Django development server if the application uses Django
 if poetry show django > /dev/null 2>&1;
 then
-  echo "Django found, starting development server..."
-  poetry run python /app/manage.py runserver "0.0.0.0:$PORT"
+  if [ -f "/app/manage.py" ]
+  then
+    echo "Django found, starting development server..."
+    poetry run python /app/manage.py runserver "0.0.0.0:$PORT"
+  else
+    echo "Django found, but /app/manage.py does not exist. Exiting..."
+    exit 1
+  fi
 fi
 
 # Try using the Flask development server if the application uses Flask
@@ -53,10 +53,15 @@ fi
 # Use a uvicorn server if the application uses FastAPI
 if poetry show fastapi > /dev/null 2>&1;
 then
-  echo "FastAPI found, starting development server..."
-  poetry run uvicorn "$APPLICATION" --workers "$WORKERS" --log-level "$LOG_LEVEL" --timeout-keep-alive "$KEEP_ALIVE" --host 0.0.0.0 --port "$PORT" --reload
+  if [ -f "/app/main.py" ]
+  then
+    echo "FastAPI found, starting development server..."
+    poetry run fastapi dev --host 0.0.0.0 --port "$PORT"
+  else
+    echo "FastAPI found, but /app/main.py does not exist. Exiting..."
+    exit 1
+  fi
 fi
 
-# Fall back to using Gunicorn
-echo "No framework found, using Gunicorn to serve development application..."
-poetry run gunicorn "$APPLICATION" --workers "$WORKERS" --threads "$THREADS" --log-level "$LOG_LEVEL" --timeout "$TIMEOUT" --keep-alive "$KEEP_ALIVE" --bind "0.0.0.0:$PORT" --worker-class="$WORKER_CLASS" --reload
+echo "No suppoorted framework found. Exiting..."
+exit 1
