Add comments to Dockerfile

diff --git a/docker/tna-python/Dockerfile b/docker/tna-python/Dockerfile
--- a/docker/tna-python/Dockerfile
+++ b/docker/tna-python/Dockerfile
@@ -1,26 +1,104 @@
 FROM python:3.11-slim
 
+# ==========================================
+# Label this container image with a semantic
+# version number
+# ==========================================
 ARG TNA_DOCKER_IMAGE_VERSION
-LABEL version="${TNA_DOCKER_IMAGE_VERSION}" \
-    org.opencontainers.image.description="National Archives base Docker image"
-EXPOSE 8080/tcp
-HEALTHCHECK CMD curl --fail http://localhost:8080/healthcheck/ || exit 1
+LABEL version="${TNA_DOCKER_IMAGE_VERSION}"
 
-ENV ENVIRONMENT=production \
-    PYTHONFAULTHANDLER=1 \
+# ==========================================
+# Add some opencontainer labels which GitHub
+# uses to display additional information
+# ==========================================
+ARG TNA_DOCKER_IMAGE_SOURCE
+LABEL org.opencontainers.image.description="National Archives base Docker image" \
+    org.opencontainers.image.source=$TNA_DOCKER_IMAGE_SOURCE \
+    org.opencontainers.image.licenses=MIT
+
+# ==========================================
+# All of our Python containers should expose
+# port 8080, which can then be mapped to any
+# other port on the host system
+# ==========================================
+EXPOSE 8080/tcp
+
+# ==========================================
+# To aid consistency Dockerised applications
+# should expose an unauthenticated URI which
+# can be used as a healthcheck by Docker and
+# other container orchestrators to check the
+# live-ness of an application - this idea is
+# based on a GOV.UK proposal:
+# https://github.com/alphagov/govuk-rfcs/blob/main/rfc-141-application-healthchecks.md
+# ==========================================
+HEALTHCHECK CMD curl --fail http://localhost:8080/healthcheck/live || exit 1
+
+# ==========================================
+# The default environment type is production
+# and something different, like "develop" or
+# "staging" will have to be given for others
+# which provides us a failsafe to ensure the
+# all our production instances will act in a
+# similar way and have the same log level
+# ==========================================
+ENV ENVIRONMENT=production
+
+# ==========================================
+# Set Python up in a consistent manner, with
+# things like ensuring no Python bytecode is
+# written to ephemeral Docker instances, and
+# allowing the output to be streamed up into
+# the terminal of the host machine
+# ==========================================
+ENV PYTHONFAULTHANDLER=1 \
     PYTHONDONTWRITEBYTECODE=1 \
     PYTHONUNBUFFERED=1 \
-    PYTHONHASHSEED=random \
-    PIP_NO_CACHE_DIR=true \
-    PIP_DISABLE_PIP_VERSION_CHECK=on \
-    POETRY_HOME=/home/app/.local \
+    PYTHONHASHSEED=random
+
+# ==========================================
+# We don't want to use a cache directory for
+# pip and we can safely ignore the check for
+# the pip version because the version of pip
+# has been defined and installed in the base
+# Python image
+# ==========================================
+ENV PIP_NO_CACHE_DIR=true \
+    PIP_DISABLE_PIP_VERSION_CHECK=on
+
+# ==========================================
+# Set up the Poetry variables so that we get
+# a consistent experience with using Poetry,
+# which includes where it will be installed,
+# where it installs the project dependencies
+# and what version is used
+# ==========================================
+ENV POETRY_HOME=/home/app/.local \
     POETRY_VERSION=1.5.1 \
     POETRY_NO_INTERACTION=1 \
     POETRY_VIRTUALENVS_CREATE=true \
     POETRY_VIRTUALENVS_IN_PROJECT=false
 
+# ==========================================
+# Ensure the `/bin/sh -c` interpreter Docker
+# executes commands through doesn't just use
+# the final operation in a pipe to determine
+# the success of the entire command
+# https://github.com/hadolint/hadolint/wiki/DL4006
+# ==========================================
 SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
+# ==========================================
+# Update the package index files and install
+# a specific version of curl that we know to
+# have no issues which is required later for
+# installing Poetry then create a new system
+# -level non-root user, a home directory for
+# "them" where we can install libraries into
+# (along with our build and run scripts) and
+# create an /app directory in the root which
+# will contain all the application code
+# ==========================================
 RUN set -eux; \
     \
     apt-get update; \
@@ -35,24 +113,58 @@ RUN set -eux; \
     chown app:app -R /app; \
     chmod 700 /app
 
-WORKDIR /app
-
+# ==========================================
+# Install Poetry in the suggested manner and
+# immediately remove the curl package, since
+# we will no longer require it and retaining
+# it could provide an unnecessary additional
+# attack vector
+# ==========================================
 RUN set -eux; \
     \
     curl -sSL "https://install.python-poetry.org" | python -; \
     apt-get remove --purge -y curl;
 
+# ==========================================
+# Change the image current working directory
+# to the new /app directory we just created,
+# ready for our application code
+# ==========================================
+WORKDIR /app
+
+# ==========================================
+# Add the Poetry binary to our path
+# ==========================================
 ENV PATH="$POETRY_HOME/bin:$PATH"
 
 # ==========================================
-# Fix for CVE-2022-40897
+# This is a temporary fix for CVE-2022-40897
 # https://access.redhat.com/security/cve/cve-2022-40897
-RUN rm -fR $POETRY_HOME/venv/lib/python3.11/site-packages/setuptools-65.5.0.dist-info
 # ==========================================
+RUN rm -fR $POETRY_HOME/venv/lib/python3.11/site-packages/setuptools-65.5.0.dist-info
 
+# ==========================================
+# Now we have finished installing everything
+# at a system level, change the current user
+# to the non-root user we created previously
+# to avoid any bad actors gaining root level
+# permissions
+# ==========================================
 USER app
 
+# ==========================================
+# Into our .local/bin/ directory copy in the
+# bash scripts we need in order to build and
+# run our application in a consistent manner
+# ==========================================
 COPY --chown=app bin/tna-build bin/tna-run /home/app/.local/bin/
 RUN chmod +x /home/app/.local/bin/tna-build /home/app/.local/bin/tna-run
 
-# CMD tail -f /dev/null
+# ==========================================
+# This does nothing but will act as a way to
+# stop the container from shutting down once
+# it has been booted which then allows us to
+# run, inspect and debug the container, even
+# though we have no application running
+# ==========================================
+CMD ["tail", "-f", "/dev/null"]
